# Form implementation generated from reading ui file 'QMenuBar菜单栏控件.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(parent=self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(parent=self.menu)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(parent=self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action1 = QtGui.QAction(parent=MainWindow)
        self.action1.setVisible(True)
        self.action1.setObjectName("action1")
        self.action2 = QtGui.QAction(parent=MainWindow)
        self.action2.setObjectName("action2")
        self.action4 = QtGui.QAction(parent=MainWindow)
        self.action4.setObjectName("action4")
        self.action3 = QtGui.QAction(parent=MainWindow)
        self.action3.setObjectName("action3")
        self.action5 = QtGui.QAction(parent=MainWindow)
        self.action5.setObjectName("action5")
        self.menu_2.addAction(self.action3)
        self.menu_2.addAction(self.action4)
        self.menu.addAction(self.action1)
        self.menu.addAction(self.action2)
        self.menu.addSeparator()
        self.menu.addAction(self.menu_2.menuAction())
        self.menu_3.addAction(self.action5)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", "学生管理"))
        self.menu_2.setTitle(_translate("MainWindow", "更多"))
        self.menu_3.setTitle(_translate("MainWindow", "关于"))
        self.action1.setText(_translate("MainWindow", "学生添加"))
        self.action2.setText(_translate("MainWindow", "学生删除"))
        self.action4.setText(_translate("MainWindow", "管理2"))
        self.action3.setText(_translate("MainWindow", "管理1"))
        self.action5.setText(_translate("MainWindow", "许可证"))
